"""Add users table and user relationships

Revision ID: 8cd45bb1dde1
Revises: 37edffa8cead
Create Date: 2025-11-13 21:51:16.481127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cd45bb1dde1'
down_revision: Union[str, Sequence[str], None] = '37edffa8cead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cross_session_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_calls_today', sa.Integer(), nullable=False),
    sa.Column('api_calls_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('saved_results', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_saved_results_user_id'), 'saved_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'saved_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_column('sessions', 'summary')
    op.drop_column('sessions', 'user_id')
    op.drop_constraint(None, 'saved_results', type_='foreignkey')
    op.drop_index(op.f('ix_saved_results_user_id'), table_name='saved_results')
    op.drop_column('saved_results', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
